language: php

services:
    - docker

env:
  matrix:
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=^6.0

matrix:
    fast_finish: true

php:
    - 7.2
    - 7.3

sudo: false

install:
    - travis_retry composer require "illuminate/support=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

before_script:
    - sudo service mysql stop
    - docker-compose -f ./tests/docker-compose.yml up -d
    - php tests/wait.php

script:
    - vendor/bin/phpunit

after_script:
    - docker-compose -f ./tests/docker-compose.yml down
